spring:
  application:
    name: sf-localstack
  datasource:
    url: jdbc:h2:mem:sfdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    async:
      request-timeout: -1

server:
  port: 8080

sf-localstack:
  api-version: v60.0
  seed-file: classpath:seed/default-seed.yml

logging:
  level:
    co.razkevich: DEBUG
